### ISSUE TITLE
Can't install due to error after askForCompass 

### ISSUE THREAD

**Issue by meliaxford** [thomasMary/generator-ionicparse#1]
Hi,
after installing with "npm install -g generator-ionicparse" I executed "yo ionicparse" and the following error occured:

yo ionicparse

events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at Object.module.exports.ask (/Users/bob/.npm-packages/lib/node_modules/generator-ionicparse/utils/compass.js:4:19)
    at module.exports.generators.Base.extend.prompting.askForCompass (/Users/bob/.npm-packages/lib/node_modules/generator-ionicparse/app/index.js:29:52)
    at /Users/bob/.npm-packages/lib/node_modules/generator-ionicparse/node_modules/yeoman-generator/lib/base.js:409:16
    at processImmediate [as _immediateCallback](timers.js:358:17)

**Comment by thomasMary** [comment]
Hi,

Sorry for that, it is still a work in progress, and not yet working. I will work on it this week end, and let you know if there is any improvement.

**Comment by TrySpaceCo** [comment]
No progress on this yet?
